allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.3.2'
  - '@bruits/satteri-darwin-arm64@0.9.1'
  - '@bruits/satteri-darwin-x64@0.9.1'
  - '@bruits/satteri-linux-x64-gnu@0.9.1'
  - '@bruits/satteri-wasm32-wasi@0.9.1'
  - '@bruits/satteri-win32-x64-msvc@0.9.1'
  - astro@7.0.2
  - satteri@0.9.1
